version: '3.9'

services:
    node:
      build: .
      environment:
        DATABASE_HOST: mysql
        DATABASE_PORT: 3306
        DATABASE_USERNAME: root
        DATABASE_PASSWORD: password
        DATABASE_NAME: my_super_app_db
      ports:
        - "3000:3000"
      depends_on:
        - mysql
        
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: my_super_app_db
      volumes:
        - db_data:/var/lib/mysql

volumes:
  db_data: